### PR TITLE
Define metadata and requirements in pyproject.toml

### PR DESCRIPTION
**Pull request by pederhan**
Removes `setup.py` and `setup.cfg`.

### CODE REVIEW

**Comment by pederhan** [comment]
```
❯ uv pip install -U -e .
   Built file:///Users/pederhan/repos/mreg-cli                                                                               Built 1 editable in 1.05s
Resolved 16 packages in 210ms
Downloaded 9 packages in 452ms
Installed 16 packages in 66ms
 + annotated-types==0.7.0
 + certifi==2024.2.2
 + charset-normalizer==3.3.2
 + dnspython==2.6.1
 + email-validator==2.1.1
 + idna==3.7
 + mreg-cli==1.0.0 (from file:///Users/pederhan/repos/mreg-cli)
 + prompt-toolkit==3.0.43
 + pydantic==2.7.1
 + pydantic-core==2.18.2
 + python-dateutil==2.9.0.post0
 + requests==2.32.2
 + six==1.16.0
 + typing-extensions==4.12.0
 + urllib3==2.2.1
 + wcwidth==0.2.13
 ```

**Comment by pederhan** [comment]
I personally also want to add this:

```toml
[project.optional-dependencies]
socks = ["PySocks>=1.7.1"]
```

Maybe even make it a required dependency? It's a pretty small dependency, and prevents future issues from people trying to use the application when working from home, etc.

**Comment by pederhan** [comment]
With the new requirements files, we could consider removing `requirements.txt` from these files:

https://github.com/unioslo/mreg-cli/blob/cd156d189ebcc4bae7f6a6986912f6796273c60b/tox.ini#L39-L41

https://github.com/unioslo/mreg-cli/blob/cd156d189ebcc4bae7f6a6986912f6796273c60b/.github/workflows/test.yml#L55-L59

However, maybe there is some value in making sure we _also_ install all the normal dependencies? 

**ALTERNATIVELY**, we don't use requirements files at all and rely on pip to resolve dependencies with `pip install '.[dev]'`?

**Review by terjekv — APPROVED** [review]
LGTM

**Pull request merged**
